### ISSUE TITLE
[BUG] set-gdm-theme make ugly transparent interface on screenshot UI

### ISSUE THREAD

**Issue by Anifyuli** [realmazharhussain/gdm-tools#18]
### What happened?

Hello, Bro.
I have problem with changing GDM theme with gdm-tools on GNOME 42. If I use it, my screenshot UI look ugly with bad transparency. I want you to fix that small problem.

### Expected behavior

You can see from this picts. I can't do it from gnome-screenshot, so I just take photo from my phone
![IMG_20220507_160507](https://user-images.githubusercontent.com/73734843/167247648-f5ba6df9-d816-47d5-872d-d85b09bcf3d0.jpg)

### To Reproduce

Enable or set a GDM theme from 3rd party theme. If reset this config to default, that problem disappear

### Detailed Explaination (Optional)

I can't describe clearly because my English is bad

### Program Version

I'm forgot what version I use 

### Source

Source code

### Environment

- OS: openSUSE Tumbleweed
- DE: GNOME 42.0

**Comment by realmazharhussain** [comment]
## Explaination
Such problems occur when the applied theme doesn't support the version of GNOME/GDM you are using. Your theme probably doesn't support GNOME 42, that's why this is happening.

While you wait for theme developer to add support for GNOME 42, this tool supports a config option `overlayMode` which can solve this problem if you set its value to `full`. This is not the default value because it can change how a theme looks.

## Step-by-Step Process

1. Open the configuration file `/etc/gdm-tools/set-gdm-theme.conf` in a text editor

   **Note:** You will need admin/root permissions to edit the file.

   **Also Note:** 
   To edit the file using the graphical text editor (GEdit), run the following command in the terminal
   ```
   gedit admin:///etc/gdm-tools/set-gdm-theme.conf
   ```
   **OR** To edit the file using a terminal text editor (nano), run the command
   ```
   sudo nano /etc/gdm-tools/set-gdm-theme.conf
   ```
2. Replace the line
   ```
   #overlayMode=resources
   ```
   with 
   ```
   overlayMode=full
   ```
   Notice: 2nd line does not have a `#` at the beginning
3. Save the file
4. Re-apply the theme

## Important Note
Change the value of `overlayMode` option back to `resources` when changing theme to one that supports GNOME 42.

**Comment by Anifyuli** [comment]
I think my theme support GNOME 42 because theme creator made commit on him repo fix to GNOME 42 support and that problem always appear

**Comment by realmazharhussain** [comment]
Which theme are you using? Can you send me a link?

**Comment by Anifyuli** [comment]
Previously I use Vimix (but it haven't commit fix GNOME 42 support) : [https://github.com/vinceliuice/vimix-gtk-themes](url)
But, I change to Graphite [https://github.com/vinceliuice/Graphite-gtk-theme](url) now and want to test it again

**Comment by Anifyuli** [comment]
I use Graphite without change `overlayMode=full`
![IMG20220507181656_11zon](https://user-images.githubusercontent.com/73734843/167252158-30c2d79d-20c1-45ca-ad60-431aa4a821c9.jpg)

But, after add `overlayMode=full` to `sudo nano /etc/gdm-tools/set-gdm-theme.conf`
![IMG20220507182030_11zon](https://user-images.githubusercontent.com/73734843/167252180-476ce6c6-7da6-414f-b179-a7ab69c27d28.jpg)

Thanks for your advice. I love it your codes

**Comment by realmazharhussain** [comment]
You are welcome!

**Comment by realmazharhussain** [comment]
I looked into both of those themes. I don't think any of them supports GNOME 42 completely. Yes, they have a few fixes for GNOME 42 but support does not seem to be complete yet.

**Comment by Anifyuli** [comment]
Oh, I see and get a your point. Thanks for your explanation. I hope you always blessed from God. Take care your health too, Bro

**Comment by realmazharhussain** [comment]
Thanks. You too.
