### ISSUE TITLE
"Show password" icon missing in gdm after setting theme.

### ISSUE THREAD

**Issue by ParaSpl01t** [realmazharhussain/gdm-tools#7]
I'm using [ZorinPurple-Dark](https://github.com/ZorinOS/zorin-desktop-themes/tree/master/ZorinPurple-Dark) Theme.
The theme is working but the "show password" icon inside the password input is showing a wierd image. (also tried with Orchis theme, still missing)

Also looks like I get an error while using `set-gdm-theme`
```
[~] ➤ set-gdm-theme -l                                                       
default
ZorinPurple-Dark
[~] ➤ set-gdm-theme -s ZorinPurple-Dark /home/paradox/Pictures/wall-blank.png
cp: cannot create regular file '/usr/share/gnome-shell/theme/gdm-background': No such file or directory
Background set to image '/home/paradox/Pictures/wall-blank.png'
Theme set to 'ZorinPurple-Dark'
```

My system:
```
[~] ➤ paru -Q | grep gdm   
gdm 40.1-2
gdm-tools-git 66.15e1065-1
libgdm 40.1-2
[~] ➤ paru -Q | grep gnome-shell
gnome-shell 1:40.4-1
```
**EDIT:** Could not find a way to take screenshot in gdm so here's a crappy photo from my phone's camera.
![20210927_180650](https://user-images.githubusercontent.com/18276917/134910013-085e0405-8ee6-45c1-b6fa-6120326fef09.jpg)

**Comment by realmazharhussain** [comment]
Actually, GDM doesn't allow theming. The way it is done in gdm-tools is to replace the default style/theme of GDM/Gnome with a custom one. So, if the custom theme does not have a specific icon, it would not show up.

Basically, the problem is not with gdm-tools but that the theme does not support new versions of Gnome.

Check if your favorite theme has a newer version available on GitHub or something that supports your version of Gnome. If yes, update it. Else, you'll have to either change GDM theme to something else or live with the weird 'show password' icon.

**Comment by sheeepdev** [comment]
https://github.com/realmazharhussain/gdm-tools/issues/9#issuecomment-928191025

**Comment by realmazharhussain** [comment]
> @sheeepdev 
> Switch to your custom icon theme and the icon will be fixed.

No, it most likely won't. 'show password' icon is part of gnome-shell theme not icon theme. I have had this problem myself in the past and the only fix that I found is what I have answered above.

**Comment by sheeepdev** [comment]
@realmazharhussain When I applied the icon theme the icon appeared

**Comment by realmazharhussain** [comment]
OK

Maybe, icon themes also include that 'show password' icon now. They didn't use to, before.
